import { ref } from 'vue'
import { defineStore } from 'pinia'

export const translations: Record<string, Record<string, string>> = {
  EN: {
    title: 'PlantVillage AI',
    subtitle: 'Disease Detection System',
    ai_powered: 'AI-Powered Diagnosis',
    identify_instantly: 'Identify plant diseases instantly',
    upload_or_speak: 'Upload a leaf photo or speak your query — get expert diagnosis in your language.',
    step1: 'STEP 1 — VALIDATION',
    image_checks: 'Image checks',
    leaf_detection: 'Leaf detection',
    quality_score: 'Image quality score',
    format_check: 'Format (JPEG/PNG/WEBP)',
    size_limit: 'File size limit',
    step2: 'STEP 2 — AI DIAGNOSIS',
    disease_id: 'Disease identification',
    deep_learning: 'Deep learning model classifies disease with Grad-CAM heatmap overlay showing affected regions',
    step3: 'STEP 3 — TREATMENT',
    hyperlocal_guidance: 'Hyperlocal guidance',
    adaptive_qa_desc: 'Adaptive Q&A determines local conditions, soil type, crop stage — then recommends actionable steps',
    diagnosis_result: 'Diagnosis Result',
    back: 'Back',
    export: 'Export',
    share: 'Share',
    disease_identified: 'Disease Identified',
    severity: 'Severity',
    consult_advisor: 'Consult Treatment Advisor',
    xai_regions: 'Explainable AI (XAI) Regions',
    xai_desc: 'Neural network diagnostic regions',
    about_disease: 'About the Disease',
    pathogen_bio: 'Pathogen Biology & Impact',
    hyperlocal_advisor: 'Hyperlocal Treatment Advisor',
    season_badge: 'Maharashtra · Kharif Season',
    adaptive_qa: 'Adaptive Q&A — Tell us your situation',
    q1: 'What is your crop growth stage?',
    q2: 'How severe is the spread?',
    q3: 'What irrigation method do you use?',
    q4: 'Access to fungicides?',
    q5: 'Recent weather?',
    generate_plan: 'Generate My Treatment Plan',
    listen_plan: 'Listen to Treatment Plan',
    download_pdf: 'Download PDF report',
    formulating_plan: 'Formulating Advisor Plan...',
    personalized_plan: 'Personalized Treatment Plan',
    voice_placeholder: 'Or answer in your language by voice',
    analyzing: 'Analyzing conditions... Formulating expert RAG advice.',
    plan_updated: 'Plan updated successfully!',

    // Disease names and options
    'Tomato Early Blight': 'Tomato Early Blight',
    'Tomato Late Blight': 'Tomato Late Blight',
    'Tomato healthy': 'Tomato healthy',
    'Early Blight': 'Early Blight',
    'Late Blight': 'Late Blight',
    'Healthy': 'Healthy',
    'Moderate': 'Moderate',
    'None': 'None',
    'Fungal pathogen': 'Fungal pathogen',
    'Alternaria solani': 'Alternaria solani',
    'Airborne spores': 'Airborne spores',
    'Warm & humid': 'Warm & humid',
    'Yield impact: High': 'Yield impact: High',
    'Pathogen detected': 'Pathogen detected',
    'Tomato': 'Tomato',
    'Apple': 'Apple',
    'Potato': 'Potato',
    'Grape': 'Grape',
    'Corn': 'Corn',
    'Cherry': 'Cherry',
    'Peach': 'Peach',
    'Pepper': 'Pepper',
    'Orange': 'Orange',
    'Blueberry': 'Blueberry',
    'Strawberry': 'Strawberry',
    'Soybean': 'Soybean',
    'Squash': 'Squash',
    'Raspberry': 'Raspberry',
    'Apple scab': 'Apple Scab',
    'Black rot': 'Black Rot',
    'Cedar apple rust': 'Cedar Apple Rust',
    'Common rust': 'Common Rust',
    'Northern Leaf Blight': 'Northern Leaf Blight',
    'Powdery mildew': 'Powdery Mildew',
    'Leaf scorch': 'Leaf Scorch',
    'Bacterial spot': 'Bacterial Spot',
    'Leaf Mold': 'Leaf Mold',
    'Septoria leaf spot': 'Septoria Leaf Spot',
    'Target Spot': 'Target Spot',
    'Tomato Yellow Leaf Curl Virus': 'Tomato Yellow Leaf Curl Virus',
    'Tomato mosaic virus': 'Tomato Mosaic Virus',
    'Cercospora leaf spot Gray leaf spot': 'Cercospora Leaf Spot / Gray Leaf Spot',
    'Esca (Black Measles)': 'Esca (Black Measles)',
    'Leaf blight (Isariopsis Leaf Spot)': 'Leaf Blight (Isariopsis Leaf Spot)',
    'Haunglongbing (Citrus greening)': 'Huanglongbing (Citrus Greening)',
    'Spider mites Two-spotted spider mite': 'Spider Mites / Two-Spotted Spider Mite',
    'Confidence': 'Confidence',
    'Record': 'Record',
    
    // Disease About narratives
    'about_early_blight': 'Early Blight (Alternaria solani) causes dark, necrotic lesions with concentric rings. It spreads rapidly in warm, humid conditions and can significantly reduce yield if untreated.',
    'about_late_blight': 'Late Blight (Phytophthora infestans) is a devastating water-mold disease causing large, water-soaked lesions on leaves and stems, with white fungal growth on leaf undersides in humid weather.',
    'about_healthy': 'The tomato plant appears healthy with green, vibrant foliage, strong stem structures, and no visible symptoms of pathogenic infection. Continue routine crop management.',

    // Explainable AI and regions
    'Leaf margin': 'Leaf margin',
    'Concentric rings': 'Concentric rings',
    'Yellowing halo': 'Yellowing halo',
    'PRIMARY REGION': 'PRIMARY REGION',
    'FEATURE DETECTED': 'FEATURE DETECTED',
    'TEXTURE': 'TEXTURE',
    'Leaf blade': 'Leaf blade',
    'RESOLUTION': 'RESOLUTION',
    'Concentric rings / texture': 'Concentric rings / texture',
    'High': 'High',
    'Medium': 'Medium',
    'Low': 'Low',
    'activation': 'activation',
    'High activation': 'High activation',
    'Low / background': 'Low / background',

    // Q&A Options
    'Seedling': 'Seedling',
    'Vegetative': 'Vegetative',
    'Flowering': 'Flowering',
    'Fruiting': 'Fruiting',
    'Few leaves': 'Few leaves',
    '~25% plant': '~25% plant',
    '50%+ plant': '50%+ plant',
    'Whole field': 'Whole field',
    'Drip': 'Drip',
    'Flood': 'Flood',
    'Sprinkler': 'Sprinkler',
    'Rainfed': 'Rainfed',
    'Yes, chemical': 'Yes, chemical',
    'Organic only': 'Organic only',
    'Limited access': 'Limited access',
    'Hot & dry': 'Hot & dry',
    'Cool & wet': 'Cool & wet',

    // Urgencies and sections
    'Immediate actions': 'Immediate actions',
    'This week': 'This week',
    'Prevention going forward': 'Prevention going forward',
    'Do today': 'Do today',
    'Mild Alert': 'Mild Alert',
    'Immediate Alert': 'Immediate Alert',

    // Toast notices
    'toast_export': 'Preparing report... Opening print dialog.',
    'toast_share': 'Successfully shared report!',
    'toast_copy': 'Result link copied to clipboard!',
    'toast_copy_failed': 'Could not copy link to clipboard.',
    'toast_pdf': 'Preparing PDF... Opening print layout.',
    
    // Image upload and voice input
    'drop_leaf': 'Drop your leaf image here',
    'or_click_browse': 'or click to browse from your device',
    'choose_image': 'Choose Image',
    'change': 'Change',
    'analyzing_dots': 'Analyzing...',
    'analyze_leaf': 'Analyze Leaf',
    'voice_input': 'Voice Input',
    'voice_tap_describe': 'Tap to describe your plant issue in your language',
    'voice_transcribing': 'Transcribing voice via OpenAI...',
    'voice_no_speech': 'Could not hear any speech. Tap to try again.',
    'voice_failed': 'Transcription failed. Please check your connection and try again.',
    'voice_listening': 'Listening... Speak now. Tap again to finish.',
    'voice_mic_denied': 'Microphone permission denied. Please allow microphone access in your browser.',
  },
  HI: {
    title: 'प्लांटविलेज AI',
    subtitle: 'रोग पहचान प्रणाली',
    ai_powered: 'एआई-संचालित निदान',
    identify_instantly: 'पौधों के रोगों की तुरंत पहचान करें',
    upload_or_speak: 'पत्ती का फोटो अपलोड करें या बोलें — अपनी भाषा में विशेषज्ञ निदान पाएं।',
    step1: 'चरण 1 — सत्यापन',
    image_checks: 'छवि की जांच',
    leaf_detection: 'पत्ती का पता लगाना',
    quality_score: 'छवि गुणवत्ता स्कोर',
    format_check: 'प्रारूप (JPEG/PNG/WEBP)',
    size_limit: 'फ़ाइल आकार सीमा',
    step2: 'चरण 2 — एआई निदान',
    disease_id: 'रोग की पहचान',
    deep_learning: 'गहन शिक्षण मॉडल प्रभावित क्षेत्रों को दिखाते हुए ग्रेड-कैम हीटमैप ओवरले के साथ रोग को वर्गीकृत करता है',
    step3: 'चरण 3 — उपचार',
    hyperlocal_guidance: 'हाइपरलोकल मार्गदर्शन',
    adaptive_qa_desc: 'अनुकूलनशील प्रश्नोत्तर स्थानीय परिस्थितियों, मिट्टी के प्रकार, फसल चरण को निर्धारित करता है — फिर कार्रवाई योग्य कदम सुझाता है',
    diagnosis_result: 'निदान परिणाम',
    back: 'पीछे',
    export: 'निर्यात करें',
    share: 'साझा करें',
    disease_identified: 'रोग की पहचान की गई',
    severity: 'तीव्रता',
    consult_advisor: 'उपचार सलाहकार से परामर्श करें',
    xai_regions: 'व्याख्यात्मक एआई (XAI) क्षेत्र',
    xai_desc: 'तंत्रिका नेटवर्क नैदानिक क्षेत्र',
    about_disease: 'रोग के बारे में',
    pathogen_bio: 'रोगजनक जीव विज्ञान और प्रभाव',
    hyperlocal_advisor: 'हाइपरलोकल उपचार सलाहकार',
    season_badge: 'महाराष्ट्र · खरीफ सीजन',
    adaptive_qa: 'अनुकूलनशील प्रश्नोत्तर — हमें अपनी स्थिति बताएं',
    q1: 'आपकी फसल की वृद्धि का चरण क्या है?',
    q2: 'फैलाव कितना गंभीर है?',
    q3: 'आप किस सिंचाई विधि का उपयोग करते हैं?',
    q4: 'कवकनाशी तक पहुंच है?',
    q5: 'हाल का मौसम कैसा है?',
    generate_plan: 'मेरा उपचार योजना तैयार करें',
    listen_plan: 'उपचार योजना सुनें',
    download_pdf: 'पीडीएफ रिपोर्ट डाउनलोड करें',
    formulating_plan: 'सलाहकार योजना तैयार की जा रही है...',
    personalized_plan: 'व्यक्तिगत उपचार योजना',
    voice_placeholder: 'या आवाज द्वारा अपनी भाषा में उत्तर दें',
    analyzing: 'परिस्थितियों का विश्लेषण... विशेषज्ञ आरएजी सलाह तैयार की जा रही है।',
    plan_updated: 'योजना सफलतापूर्वक अपडेट की गई!',

    // Disease names and options
    'Tomato Early Blight': 'टमाटर का अगेती झुलसा (Early Blight)',
    'Tomato Late Blight': 'टमाटर का पछेती झुलसा (Late Blight)',
    'Tomato healthy': 'टमाटर स्वस्थ (Tomato healthy)',
    'Early Blight': 'अगेती झुलसा (Early Blight)',
    'Late Blight': 'पछेती झुलसा (Late Blight)',
    'Healthy': 'स्वस्थ (Healthy)',
    'Moderate': 'मध्यम',
    'None': 'कोई नहीं',
    'Fungal pathogen': 'कवक रोगजनक',
    'Alternaria solani': 'अल्टरनेरिया सोलानी',
    'Airborne spores': 'हवा में फैलने वाले बीजाणु',
    'Warm & humid': 'गर्म और नम',
    'Yield impact: High': 'उपज पर प्रभाव: उच्च',
    'Pathogen detected': 'रोगजनक का पता चला',
    'Tomato': 'टमाटर',
    'Apple': 'सेब',
    'Potato': 'आलू',
    'Grape': 'अंगूर',
    'Corn': 'मक्का',
    'Cherry': 'चेरी',
    'Peach': 'आडू',
    'Pepper': 'शिमला मिर्च',
    'Orange': 'संतरा',
    'Blueberry': 'ब्लूबेरी',
    'Strawberry': 'स्ट्रॉबेरी',
    'Soybean': 'सोयाबीन',
    'Squash': 'कद्दू',
    'Raspberry': 'रास्पबेरी',
    'Apple scab': 'सेब का स्कैब (Apple Scab)',
    'Black rot': 'ब्लैक रॉट (Black Rot)',
    'Cedar apple rust': 'सीडर एप्पल रस्ट',
    'Common rust': 'कॉमन रस्ट',
    'Northern Leaf Blight': 'उत्तरी पत्ती झुलसा',
    'Powdery mildew': 'पाउडर जैसी फफूंदी (Powdery Mildew)',
    'Leaf scorch': 'पत्ती का झुलसना (Leaf Scorch)',
    'Bacterial spot': 'जीवाणु जनित धब्बा (Bacterial Spot)',
    'Leaf Mold': 'लीफ मोल्ड',
    'Septoria leaf spot': 'सेप्टोरिया लीफ स्पॉट',
    'Target Spot': 'टारगेट स्पॉट',
    'Tomato Yellow Leaf Curl Virus': 'टमाटर पीला पत्ती सुकड़न वायरस',
    'Tomato mosaic virus': 'टमाटर मोज़ेक वायरस',
    'Cercospora leaf spot Gray leaf spot': 'सर्कॉस्पोरा पत्ती धब्बा / ग्रे पत्ती धब्बा (Gray Leaf Spot)',
    'Esca (Black Measles)': 'एस्का (काला खसरा)',
    'Leaf blight (Isariopsis Leaf Spot)': 'पत्ती झुलसा (इसारियोप्सिस लीफ स्पॉट)',
    'Haunglongbing (Citrus greening)': 'हुआंगलोंगबिंग (सिट्रस ग्रीनिंग)',
    'Spider mites Two-spotted spider mite': 'मकड़ी के कण (दो-चित्तीदार मकड़ी का कण)',
    'Confidence': 'विश्वास स्तर',
    'Record': 'रिकॉर्ड आईडी',
    
    // Disease About narratives
    'about_early_blight': 'अगेती झुलसा (अल्टरनेरिया सोलानी) के कारण गहरे, संकेंद्रीय छल्लों वाले मृत धब्बे बनते हैं। यह गर्म और नम परिस्थितियों में तेजी से फैलता है और यदि अनुपचारित छोड़ दिया जाए तो उपज को काफी कम कर सकता है।',
    'about_late_blight': 'पछेती झुलसा (फाइटोफ्थोरा इन्फेस्टन्स) एक विनाशकारी जल-मोल्ड रोग है जिसके कारण पत्तियों और तनों पर बड़े, पानी से भीगे हुए धब्बे बन जाते हैं, और नम मौसम में पत्तियों के नीचे सफेद कवक की वृद्धि होती है।',
    'about_healthy': 'टमाटर का पौधा हरी, जीवंत पत्तियों, मजबूत तने की संरचना और रोगजनक संक्रमण के किसी भी दृश्य लक्षण के बिना स्वस्थ दिखाई देता है। नियमित फसल प्रबंधन जारी रखें।',

    // Explainable AI and regions
    'Leaf margin': 'पत्ती का किनारा',
    'Concentric rings': 'संकेंद्रित छल्ले',
    'Yellowing halo': 'पीला प्रभाव मंडल',
    'PRIMARY REGION': 'प्राथमिक क्षेत्र',
    'FEATURE DETECTED': 'पहचाना गया लक्षण',
    'TEXTURE': 'बनावट',
    'Leaf blade': 'पत्ती का फलक',
    'RESOLUTION': 'संकल्प',
    'Concentric rings / texture': 'संकेंद्रित छल्ले / बनावट',
    'High': 'उच्च',
    'Medium': 'मध्यम',
    'Low': 'कम',
    'activation': 'सक्रियता',
    'High activation': 'उच्च सक्रियता',
    'Low / background': 'कम / पृष्ठभूमि',

    // Q&A Options
    'Seedling': 'अंकुर (Seedling)',
    'Vegetative': 'वानस्पतिक (Vegetative)',
    'Flowering': 'फूल आना (Flowering)',
    'Fruiting': 'फल आना (Fruiting)',
    'Few leaves': 'कुछ पत्तियां',
    '~25% plant': '~25% पौधा',
    '50%+ plant': '50%+ पौधा',
    'Whole field': 'पूरा खेत',
    'Drip': 'टपक (Drip)',
    'Flood': 'बाढ़ (Flood)',
    'Sprinkler': 'छिड़काव (Sprinkler)',
    'Rainfed': 'वर्षा आधारित',
    'Yes, chemical': 'हाँ, रासायनिक',
    'Organic only': 'केवल जैविक',
    'Limited access': 'सीमित पहुंच',
    'Hot & dry': 'गर्म और शुष्क',
    'Cool & wet': 'ठंडा और गीला',

    // Urgencies and sections
    'Immediate actions': 'तत्काल कार्रवाई',
    'This week': 'इस सप्ताह',
    'Prevention going forward': 'भविष्य में रोकथाम',
    'Do today': 'आज ही करें',
    'Mild Alert': 'हल्का अलर्ट',
    'Immediate Alert': 'तत्काल अलर्ट',

    // Toast notices
    'toast_export': 'रिपोर्ट तैयार की जा रही है... प्रिंट डायलॉग खुल रहा है।',
    'toast_share': 'सफलतापूर्वक रिपोर्ट साझा की गई!',
    'toast_copy': 'परिणाम लिंक क्लिपबोर्ड पर कॉपी किया गया!',
    'toast_copy_failed': 'क्लिपबोर्ड पर लिंक कॉपी नहीं किया जा सका।',
    'toast_pdf': 'पीडीएफ तैयार की जा रही है... प्रिंट लेआउट खुल रहा है।',

    // Image upload and voice input
    'drop_leaf': 'अपनी पत्ती की छवि यहाँ डालें',
    'or_click_browse': 'या अपने डिवाइस से चुनने के लिए क्लिक करें',
    'choose_image': 'छवि चुनें',
    'change': 'बदलें',
    'analyzing_dots': 'विश्लेषण किया जा रहा है...',
    'analyze_leaf': 'पत्ती का विश्लेषण करें',
    'voice_input': 'आवाज़ इनपुट',
    'voice_tap_describe': 'अपनी भाषा में पौधे की समस्या बताने के लिए टैप करें',
    'voice_transcribing': 'ओपनएआई के माध्यम से आवाज़ को लिखा जा रहा है...',
    'voice_no_speech': 'कोई आवाज़ सुनाई नहीं दी। फिर से प्रयास करने के लिए टैप करें।',
    'voice_failed': 'अनुलेखन विफल रहा। कृपया अपना कनेक्शन जांचें और पुनः प्रयास करें।',
    'voice_listening': 'सुन रहा हूँ... अब बोलें। समाप्त करने के लिए फिर से टैप करें।',
    'voice_mic_denied': 'माइक्रोफ़ोन अनुमति अस्वीकृत। कृपया अपने ब्राउज़र में माइक्रोफ़ोन एक्सेस की अनुमति दें।',
  },
  MR: {
    title: 'प्लांटव्हिलेज AI',
    subtitle: 'रोग निदान प्रणाली',
    ai_powered: 'एआय-आधारित निदान',
    identify_instantly: 'झाडांच्या रोगांची त्वरित ओळख करा',
    upload_or_speak: 'पानाचा फोटो अपलोड करा किंवा बोला — आपल्या भाषेत तज्ज्ञ निदान मिळवा।',
    step1: 'पायरी १ — पडताळणी',
    image_checks: 'फोटो तपासणी',
    leaf_detection: 'पानाची ओळख',
    quality_score: 'फोटो गुणवत्ता स्कोर',
    format_check: 'प्रारूप (JPEG/PNG/WEBP)',
    size_limit: 'फाईल साईझ मर्यादा',
    step2: 'पायरी २ — एआय निदान',
    disease_id: 'रोगाची ओळख',
    deep_learning: 'डीप लर्निंग मॉडेल प्रभावित भाग दर्शविणाऱ्या ग्रेड-कॅम हीटमॅप ओव्हरलेसह रोगाचे वर्गीकरण करते',
    step3: 'पायरी ३ — उपचार',
    hyperlocal_guidance: 'स्थानिक मार्गदर्शन',
    adaptive_qa_desc: 'अनुकूलनशील प्रश्नोत्तर स्थानिक परिस्थिती, मातीचा प्रकार, पिकाची स्थिती ठरवते — आणि कृती आराखडा सुचवते',
    diagnosis_result: 'निदान निकाल',
    back: 'मागे',
    export: 'डाऊनलोड',
    share: 'शेअर',
    disease_identified: 'रोगाचे निदान झाले',
    severity: 'तीव्रता',
    consult_advisor: 'उपचार सल्लागाराशी चर्चा करा',
    xai_regions: 'स्पष्टीकरण देणारे एआय (XAI) क्षेत्र',
    xai_desc: 'न्यूरल नेटवर्क निदान क्षेत्र',
    about_disease: 'रोगाबद्दल माहिती',
    pathogen_bio: 'रोगजनक जीवशास्त्र आणि प्रभाव',
    hyperlocal_advisor: 'स्थानिक उपचार सल्लागार',
    season_badge: 'महाराष्ट्र · खरीप हंगाम',
    adaptive_qa: 'अनुकूलनशील प्रश्नोत्तर — आम्हाला आपली परिस्थिती सांगा',
    q1: 'तुमच्या पिकाची वाढ कोणत्या टप्प्यावर आहे?',
    q2: 'रोगाचा प्रसार किती गंभीर आहे?',
    q3: 'तुम्ही कोणत्या सिंचन पद्धतीचा वापर करता?',
    q4: 'बुरशीनाशक औषधांची उपलब्धता आहे का?',
    q5: 'सध्याचे हवामान कसे आहे?',
    generate_plan: 'माझा उपचार आराखडा तयार करा',
    listen_plan: 'उपचार आराखडा ऐका',
    download_pdf: 'पीडीएफ रिपोर्ट डाऊनलोड करा',
    formulating_plan: 'सल्लागार आराखडा तयार केला जात आहे...',
    personalized_plan: 'वैयक्तिकृत उपचार आराखडा',
    voice_placeholder: 'किंवा आपल्या भाषेत आवाजाद्वारे उत्तर द्या',
    analyzing: 'परिस्थितीचे विश्लेषण... तज्ज्ञ आरएजी सल्ला तयार केला जात आहे।',
    plan_updated: 'आराखडा यशस्वीरित्या तयार केला गेला!',

    // Disease names and options
    'Tomato Early Blight': 'टोमॅटोवरील लवकर येणारा करपा (Early Blight)',
    'Tomato Late Blight': 'टोमॅटोवरील उशिरा येणारा करपा (Late Blight)',
    'Tomato healthy': 'टोमॅटो निरोगी (Tomato healthy)',
    'Early Blight': 'लवकर येणारा करपा (Early Blight)',
    'Late Blight': 'उशिरा येणारा करपा (Late Blight)',
    'Healthy': 'निरोगी (Healthy)',
    'Moderate': 'मध्यम',
    'None': 'काही नाही',
    'Fungal pathogen': 'बुरशीजन्य रोगजनक',
    'Alternaria solani': 'अल्टरनेरिया सोलानी',
    'Airborne spores': 'हवेतील बीजाणू',
    'Warm & humid': 'उबदार आणि दमट',
    'Yield impact: High': 'उत्पादनावर परिणाम: उच्च',
    'Pathogen detected': 'रोगजनक आढळला',
    'Tomato': 'टोमॅटो',
    'Apple': 'सफरचंद',
    'Potato': 'बटाटा',
    'Grape': 'द्राक्षे',
    'Corn': 'मका',
    'Cherry': 'चेरी',
    'Peach': 'आडू',
    'Pepper': 'ढोबळी मिरची',
    'Orange': 'संत्री',
    'Blueberry': 'ब्लूबेरी',
    'Strawberry': 'स्ट्रॉबेरी',
    'Soybean': 'सोयाबीन',
    'Squash': 'भोपळा',
    'Raspberry': 'रास्पबेरी',
    'Apple scab': 'सफरचंदावरील खरुज (Apple Scab)',
    'Black rot': 'काळा कुजणे (Black Rot)',
    'Cedar apple rust': 'सीडर एप्पल रस्ट',
    'Common rust': 'कॉमन रस्ट',
    'Northern Leaf Blight': 'उत्तरी पानांवरील करपा',
    'Powdery mildew': 'भुरी रोग (Powdery Mildew)',
    'Leaf scorch': 'पाने जळणे (Leaf Scorch)',
    'Bacterial spot': 'जिवाणूजन्य ठिपके (Bacterial Spot)',
    'Leaf Mold': 'पानांवरील बुरशी',
    'Septoria leaf spot': 'सेप्टोरिया पानांवरील ठिपके',
    'Target Spot': 'टारगेट स्पॉट',
    'Tomato Yellow Leaf Curl Virus': 'टोमॅटो पिवळा पर्णगुच्छ व्हायरस',
    'Tomato mosaic virus': 'टोमॅटो मोझॅक व्हायरस',
    'Cercospora leaf spot Gray leaf spot': 'सर्कॉस्पोरा पानांवरील ठिपके / ग्रे पानांवरील ठिपके',
    'Esca (Black Measles)': 'एस्का (काळा गोवर)',
    'Leaf blight (Isariopsis Leaf Spot)': 'पानांवरील करपा (इसारिओप्सिस पानांवरील ठिपके)',
    'Haunglongbing (Citrus greening)': 'हुआंगलाँगबिंग (सिट्रस ग्रीनिंग)',
    'Spider mites Two-spotted spider mite': 'कोळी कीड (दोन ठिपक्यांची कोळी कीड)',
    'Confidence': 'विश्वासार्हता',
    'Record': 'नोंद आयडी',
    
    // Disease About narratives
    'about_early_blight': 'लवकर येणाऱ्या करप्यामुळे (अल्टरनेरिया सोलानी) पानांवर पानांवर गडद, संकेंद्री कड्यांचे मृत ठिपके पडतात. हे उबदार आणि दमट वातावरणात वेगाने पसरते आणि उपचार न केल्यास उत्पादनात लक्षणीय घट करू शकते.',
    'about_late_blight': 'उशिरा येणारा करपा (फायटोफ्थोरा इन्फेस्टन्स) हा एक विनाशकारी जल-बुरशीजन्य रोग आहे ज्यामुळे पानांवर आणि खोडांवर मोठे, पाण्याचे डाग पडतात आणि दमट हवामानात पानाच्या खालच्या बाजूला पांढरी बुरशी वाढते.',
    'about_healthy': 'टोमॅटोचे रोप हिरवेगार, दोलायमान पानांसह, मजबूत खोड रचनेसह आणि रोगजनक संसर्गाचे कोणतेही दृश्य लक्षण नसलेले निरोगी दिसते. नियमित पीक व्यवस्थापन चालू ठेवा.',

    // Explainable AI and regions
    'Leaf margin': 'पानाची कडा',
    'Concentric rings': 'संकेंद्री कडे',
    'Yellowing halo': 'पिवळसर कडा',
    'PRIMARY REGION': 'प्राथमिक क्षेत्र',
    'FEATURE DETECTED': 'आढळलेले वैशिष्ट्य',
    'TEXTURE': 'पोत',
    'Leaf blade': 'पानाचे पाते',
    'RESOLUTION': 'रिझोल्यूशन',
    'Concentric rings / texture': 'संकेंद्री कडे / पोत',
    'High': 'उच्च',
    'Medium': 'मध्यम',
    'Low': 'कमी',
    'activation': 'सक्रियता',
    'High activation': 'उच्च सक्रियता',
    'Low / background': 'कमी / पार्श्वभूमी',

    // Q&A Options
    'Seedling': 'रोपटे (Seedling)',
    'Vegetative': 'वानस्पतिक वाढ (Vegetative)',
    'Flowering': 'फुलोरा (Flowering)',
    'Fruiting': 'फळ धारणा (Fruiting)',
    'Few leaves': 'काही पाने',
    '~25% plant': '~25% रोप',
    '50%+ plant': '50%+ रोप',
    'Whole field': 'संपूर्ण शेत',
    'Drip': 'ठिबक (Drip)',
    'Flood': 'पूर पाणी (Flood)',
    'Sprinkler': 'तुषार (Sprinkler)',
    'Rainfed': 'पावसावर अवलंबून',
    'Yes, chemical': 'होय, रासायनिक',
    'Organic only': 'फक्त सेंद्रिय',
    'Limited access': 'मर्यादित उपलब्धता',
    'Hot & dry': 'उष्ण आणि कोरडे',
    'Cool & wet': 'थंड आणि ओले',

    // Urgencies and sections
    'Immediate actions': 'तात्काळ उपाय',
    'This week': 'या आठवड्यात',
    'Prevention going forward': 'पुढील प्रतिबंधात्मक उपाय',
    'Do today': 'आजच करा',
    'Mild Alert': 'सौम्य इशारा',
    'Immediate Alert': 'तात्काळ इशारा',

    // Toast notices
    'toast_export': 'अहवाल तयार केला जात आहे... प्रिंट डायलॉग उघडत आहे.',
    'toast_share': 'अहवाल यशस्वीरित्या शेअर केला गेला!',
    'toast_copy': 'निकाल लिंक क्लिपबोर्डवर कॉपी केली गेली!',
    'toast_copy_failed': 'क्लिपबोर्डवर लिंक कॉपी करता आली नाही.',
    'toast_pdf': 'पीडीएफ तयार केली जात आहे... प्रिंट लेआउट उघडत आहे.',

    // Image upload and voice input
    'drop_leaf': 'तुमच्या पानाचा फोटो येथे टाका',
    'or_click_browse': 'किंवा तुमच्या डिव्हाइसवरून निवडण्यासाठी क्लिक करा',
    'choose_image': 'फोटो निवडा',
    'change': 'बदला',
    'analyzing_dots': 'विश्लेषण केले जात आहे...',
    'analyze_leaf': 'पानाचे विश्लेषण करा',
    'voice_input': 'व्हॉईस इनपुट',
    'voice_tap_describe': 'तुमच्या भाषेत झाडाची समस्या सांगण्यासाठी टॅप करा',
    'voice_transcribing': 'ओपनएआयद्वारे आवाजाचे भाषांतर केले जात आहे...',
    'voice_no_speech': 'कोणताही आवाज ऐकू आला नाही. पुन्हा प्रयत्न करण्यासाठी टॅप करा.',
    'voice_failed': 'भाषांतर अयशस्वी झाले. कृपया तुमचे कनेक्शन तपासा आणि पुन्हा प्रयत्न करा.',
    'voice_listening': 'ऐकत आहे... आता बोला. पूर्ण करण्यासाठी पुन्हा टॅप करा.',
    'voice_mic_denied': 'मायक्रोफोन परवानगी नाकारली. कृपया तुमच्या ब्राउझरमध्ये मायक्रोफोन प्रवेशास परवानगी द्या.',
  }
}

export const useLanguageStore = defineStore('language', () => {
  const currentLanguage = ref<[string, string]>(['English', 'EN'])

  const setLanguage = (lang: [string, string]) => {
    currentLanguage.value = lang
  }

  const t = (key: string): string => {
    const code = currentLanguage.value[1]
    const dict = translations[code] || translations.EN || {}
    const defaultDict = translations.EN || {}
    return dict[key] || defaultDict[key] || key
  }

  return {
    currentLanguage,
    setLanguage,
    t
  }
})
